-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-02 19:57:19 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE companhia_aerea (
    nome_comp   VARCHAR2(15),
    id_comp     VARCHAR2(15) NOT NULL,
    pais_origem VARCHAR2(15),
    info_ctt    VARCHAR2(10)
);

ALTER TABLE companhia_aerea ADD CONSTRAINT companhia_aerea_pk PRIMARY KEY ( id_comp );

CREATE TABLE passageiros (
    id_passageiro VARCHAR2(11) NOT NULL,
    nome          VARCHAR2(10),
    email         VARCHAR2(15),
    num_telefone  VARCHAR2(15)
);

ALTER TABLE passageiros ADD CONSTRAINT passageiros_pk PRIMARY KEY ( id_passageiro );

CREATE TABLE reserevas (
    info_voo                  VARCHAR2(20),
    num_acessentos_reservados VARCHAR2(310),
    status_reserva            VARCHAR2(10),
    voos_numero_voo           VARCHAR2(4) NOT NULL,
    voos_origem               VARCHAR2(10) NOT NULL,
    passageiros_id_passageiro VARCHAR2(11)
);

CREATE TABLE voos (
    numero_voo              VARCHAR2(4) NOT NULL,
    origem                  VARCHAR2(10) NOT NULL,
    destino                 VARCHAR2(10),
    dhp                     DATE,
    dhc                     DATE,
    num_assentos            VARCHAR2(350) 
--  ERROR: VARCHAR2 size not specified 
    ,
    companhia_aerea_id_comp VARCHAR2(15) NOT NULL
);

ALTER TABLE voos ADD CONSTRAINT voos_pk PRIMARY KEY ( numero_voo,
                                                      origem );

ALTER TABLE reserevas
    ADD CONSTRAINT reserevas_passageiros_fk FOREIGN KEY ( passageiros_id_passageiro )
        REFERENCES passageiros ( id_passageiro );

ALTER TABLE reserevas
    ADD CONSTRAINT reserevas_voos_fk FOREIGN KEY ( voos_numero_voo,
                                                   voos_origem )
        REFERENCES voos ( numero_voo,
                          origem );

ALTER TABLE voos
    ADD CONSTRAINT voos_companhia_aerea_fk FOREIGN KEY ( companhia_aerea_id_comp )
        REFERENCES companhia_aerea ( id_comp );
        
-------------------------------------------------------------
Insert into  passageiros(ID_PASSAGEIRO,NOME,EMAIL,NUM_TELEFONE)
values (1,'Pedro','ph.vinatge@',119963511701)
        
Insert into  passageiros(ID_PASSAGEIRO,NOME,EMAIL,NUM_TELEFONE)
values (2,'talita','talita.fbeck',119963511711); 

Insert into  passageiros(ID_PASSAGEIRO,NOME,EMAIL,NUM_TELEFONE)
values (3,'felipe','felipeAmador',119963511712);
        
----------------------------------------------------------------------

desc companhia_aerea
insert into companhia_aerea(NOME_COMP,ID_COMP,PAIS_ORIGEM,INFO_CTT)values
('Luftanhsa',79934,'russia',789589);

insert into companhia_aerea(NOME_COMP,ID_COMP,PAIS_ORIGEM,INFO_CTT)values
('Air mexico',996358,'México',796378);

insert into companhia_aerea(NOME_COMP,ID_COMP,PAIS_ORIGEM,INFO_CTT)values
('Gol',126741,'Timor',2569874);

-----------------------------------------------------------------
desc voos
insert into voos(numero_voo,origem,destino,dhp,dhc ,num_assentos,COMPANHIA_AEREA_ID_COMP
)values  (1,'russia','brasil', to_date('19/10/2003 19:10:55','dd/mm/yyyy  hh24:mi:ss'),to_date('30/10/2003 19:30:55','dd/mm/yyyy  hh24:mi:ss'),371,79934);

insert into voos(numero_voo,origem,destino,dhp,dhc ,num_assentos,COMPANHIA_AEREA_ID_COMP
)values 
(50,'Ucrania','china', to_date('01/5/2005 20:10:55','dd/mm/yyyy  hh24:mi:ss'),
to_date('15/5/2005 23:35:55','dd/mm/yyyy  hh24:mi:ss'),360,996358);

insert into voos(numero_voo,origem,destino,dhp,dhc ,num_assentos,COMPANHIA_AEREA_ID_COMP
)values 
(65,'EUA','japão', to_date('14/4/2014 20:30:55','dd/mm/yyyy  hh24:mi:ss'),
to_date('20/5/2014 23:20:55','dd/mm/yyyy  hh24:mi:ss'),365,126741);

select * from companhia_aerea;


--------------------------------
insert into reserevas(info_voo,num_acessentos_reservados,status_reserva,
voos_numero_voo,voos_origem,passageiros_id_passageiro)
values 
('hab',300,'reservado',65,'EUA',1);
desc reserevas

insert into reserevas(info_voo,num_acessentos_reservados,status_reserva,
voos_numero_voo,voos_origem,passageiros_id_passageiro)
values 
('hab',370,'livre',50,'Ucrania',2);


insert into reserevas(info_voo,num_acessentos_reservados,status_reserva,
voos_numero_voo,voos_origem,passageiros_id_passageiro)
values 
('hab',355,'reservado',1,'russia',3);

Commit
------------------------------------ex 2--------------------------------

UPDATE voos
SET destino = 'Argentina'
WHERE numero_voo = 65;

UPDATE passageiros
SET EMAIL = 'Soarers@',
NUM_TELEFONE = '7996527'
WHERE ID_PASSAGEIRO = 1;

--------------------ex 3------------------------------
DELETE FROM PASSAGEIROS
WHERE id_passageiro = 1;
---não foi possivel pois esta vinculado a uma entidade child usada em outra tabela


DELETE FROM companhia_aerea
WHERE ID_COMP = 2;
-- Não, pois não usei 2 como id da compahnia, mas caso tivesse não seria possivel também , pois estaria vinculado a outra tabela tambem.






-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              6
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
